/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsamistore_mockup.panels;

import dsamistore_mockup.*;
import java.awt.BorderLayout;


/**
 *
 * @author OSCAR
 */
public class aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form crud
     */
    public aplicacion() {
        initComponents();
        setSize(1060, 716);
        
        categoria categoria = new categoria();
        categoria.setSize(875, 629);
        
        content.removeAll();
        content.add(categoria,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jp_productos = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        btn_producto_agregar = new javax.swing.JButton();
        txtCategoriaBuscar4 = new javax.swing.JTextField();
        btn_producto_buscar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_categoria2 = new javax.swing.JTable();
        jp_empleados = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        btn_empleado_agregar = new javax.swing.JButton();
        txtCategoriaBuscar2 = new javax.swing.JTextField();
        btn_empleado_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_empleado = new javax.swing.JTable();
        jp_roles = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        btn_roles_agregar = new javax.swing.JButton();
        txtCategoriaBuscar3 = new javax.swing.JTextField();
        btn_roles_buscar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_roles = new javax.swing.JTable();
        jp_usuarios = new javax.swing.JPanel();
        btn_usuario_agregar = new javax.swing.JButton();
        txtCategoriaBuscar = new javax.swing.JTextField();
        btn_usuario_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_usuario = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jp_categorias = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        btn_categoria_agregar = new javax.swing.JButton();
        txtCategoriaBuscar1 = new javax.swing.JTextField();
        btn_categoria_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_categoria1 = new javax.swing.JTable();
        formCrud = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        t = new javax.swing.JPanel();
        btnCategorias = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnIconSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jp_productos.setBackground(new java.awt.Color(255, 255, 255));
        jp_productos.setName("jp_productos"); // NOI18N

        label5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label5.setText("Producto");

        btn_producto_agregar.setBackground(new java.awt.Color(34, 197, 94));
        btn_producto_agregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_producto_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_producto_agregar.setText("AGREGAR");
        btn_producto_agregar.setToolTipText("");
        btn_producto_agregar.setAutoscrolls(true);
        btn_producto_agregar.setBorder(null);
        btn_producto_agregar.setBorderPainted(false);
        btn_producto_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_producto_buscar.setBackground(new java.awt.Color(34, 197, 94));
        btn_producto_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_producto_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_producto_buscar.setText("BUSCAR");
        btn_producto_buscar.setToolTipText("");
        btn_producto_buscar.setAutoscrolls(true);
        btn_producto_buscar.setBorder(null);
        btn_producto_buscar.setBorderPainted(false);
        btn_producto_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb_categoria2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Acciones"
            }
        ));
        jScrollPane5.setViewportView(tb_categoria2);

        javax.swing.GroupLayout jp_productosLayout = new javax.swing.GroupLayout(jp_productos);
        jp_productos.setLayout(jp_productosLayout);
        jp_productosLayout.setHorizontalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_productosLayout.createSequentialGroup()
                        .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_productosLayout.createSequentialGroup()
                                .addComponent(btn_producto_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtCategoriaBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_producto_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jp_productosLayout.setVerticalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_producto_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_producto_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_empleados.setBackground(new java.awt.Color(255, 255, 255));

        label3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label3.setText("Empleado");

        btn_empleado_agregar.setBackground(new java.awt.Color(34, 197, 94));
        btn_empleado_agregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_empleado_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_empleado_agregar.setText("AGREGAR");
        btn_empleado_agregar.setToolTipText("");
        btn_empleado_agregar.setAutoscrolls(true);
        btn_empleado_agregar.setBorder(null);
        btn_empleado_agregar.setBorderPainted(false);
        btn_empleado_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_empleado_buscar.setBackground(new java.awt.Color(34, 197, 94));
        btn_empleado_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_empleado_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_empleado_buscar.setText("BUSCAR");
        btn_empleado_buscar.setToolTipText("");
        btn_empleado_buscar.setAutoscrolls(true);
        btn_empleado_buscar.setBorder(null);
        btn_empleado_buscar.setBorderPainted(false);
        btn_empleado_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Acciones"
            }
        ));
        jScrollPane3.setViewportView(tb_empleado);

        javax.swing.GroupLayout jp_empleadosLayout = new javax.swing.GroupLayout(jp_empleados);
        jp_empleados.setLayout(jp_empleadosLayout);
        jp_empleadosLayout.setHorizontalGroup(
            jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empleadosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_empleadosLayout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_empleadosLayout.createSequentialGroup()
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_empleadosLayout.createSequentialGroup()
                                .addComponent(btn_empleado_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtCategoriaBuscar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_empleado_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jp_empleadosLayout.setVerticalGroup(
            jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empleadosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_empleado_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_empleado_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_roles.setBackground(new java.awt.Color(255, 255, 255));

        label4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label4.setText("Roles");

        btn_roles_agregar.setBackground(new java.awt.Color(34, 197, 94));
        btn_roles_agregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_roles_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_roles_agregar.setText("AGREGAR");
        btn_roles_agregar.setToolTipText("");
        btn_roles_agregar.setAutoscrolls(true);
        btn_roles_agregar.setBorder(null);
        btn_roles_agregar.setBorderPainted(false);
        btn_roles_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_roles_buscar.setBackground(new java.awt.Color(34, 197, 94));
        btn_roles_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_roles_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_roles_buscar.setText("BUSCAR");
        btn_roles_buscar.setToolTipText("");
        btn_roles_buscar.setAutoscrolls(true);
        btn_roles_buscar.setBorder(null);
        btn_roles_buscar.setBorderPainted(false);
        btn_roles_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb_roles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Acciones"
            }
        ));
        jScrollPane4.setViewportView(tb_roles);

        javax.swing.GroupLayout jp_rolesLayout = new javax.swing.GroupLayout(jp_roles);
        jp_roles.setLayout(jp_rolesLayout);
        jp_rolesLayout.setHorizontalGroup(
            jp_rolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_rolesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_rolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_rolesLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_rolesLayout.createSequentialGroup()
                        .addGroup(jp_rolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_rolesLayout.createSequentialGroup()
                                .addComponent(btn_roles_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtCategoriaBuscar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_roles_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jp_rolesLayout.setVerticalGroup(
            jp_rolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_rolesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_rolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_roles_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_roles_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_usuarios.setBackground(new java.awt.Color(255, 255, 255));

        btn_usuario_agregar.setBackground(new java.awt.Color(34, 197, 94));
        btn_usuario_agregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_usuario_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_usuario_agregar.setText("AGREGAR");
        btn_usuario_agregar.setToolTipText("");
        btn_usuario_agregar.setAutoscrolls(true);
        btn_usuario_agregar.setBorder(null);
        btn_usuario_agregar.setBorderPainted(false);
        btn_usuario_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_usuario_buscar.setBackground(new java.awt.Color(34, 197, 94));
        btn_usuario_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_usuario_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_usuario_buscar.setText("BUSCAR");
        btn_usuario_buscar.setToolTipText("");
        btn_usuario_buscar.setAutoscrolls(true);
        btn_usuario_buscar.setBorder(null);
        btn_usuario_buscar.setBorderPainted(false);
        btn_usuario_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(tb_usuario);

        label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label1.setText("Usuario");

        javax.swing.GroupLayout jp_usuariosLayout = new javax.swing.GroupLayout(jp_usuarios);
        jp_usuarios.setLayout(jp_usuariosLayout);
        jp_usuariosLayout.setHorizontalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_usuariosLayout.createSequentialGroup()
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_usuariosLayout.createSequentialGroup()
                                .addComponent(btn_usuario_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtCategoriaBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_usuario_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jp_usuariosLayout.setVerticalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_usuario_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jp_categorias.setBackground(new java.awt.Color(255, 255, 255));
        jp_categorias.setName("jp_categorias"); // NOI18N

        label2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label2.setText("Categoria");

        btn_categoria_agregar.setBackground(new java.awt.Color(34, 197, 94));
        btn_categoria_agregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_categoria_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_categoria_agregar.setText("AGREGAR");
        btn_categoria_agregar.setToolTipText("");
        btn_categoria_agregar.setAutoscrolls(true);
        btn_categoria_agregar.setBorder(null);
        btn_categoria_agregar.setBorderPainted(false);
        btn_categoria_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categoria_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoria_agregarActionPerformed(evt);
            }
        });

        btn_categoria_buscar.setBackground(new java.awt.Color(34, 197, 94));
        btn_categoria_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_categoria_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_categoria_buscar.setText("BUSCAR");
        btn_categoria_buscar.setToolTipText("");
        btn_categoria_buscar.setAutoscrolls(true);
        btn_categoria_buscar.setBorder(null);
        btn_categoria_buscar.setBorderPainted(false);
        btn_categoria_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb_categoria1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Acciones"
            }
        ));
        jScrollPane2.setViewportView(tb_categoria1);

        javax.swing.GroupLayout jp_categoriasLayout = new javax.swing.GroupLayout(jp_categorias);
        jp_categorias.setLayout(jp_categoriasLayout);
        jp_categoriasLayout.setHorizontalGroup(
            jp_categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_categoriasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_categoriasLayout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_categoriasLayout.createSequentialGroup()
                        .addGroup(jp_categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_categoriasLayout.createSequentialGroup()
                                .addComponent(btn_categoria_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCategoriaBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_categoria_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jp_categoriasLayout.setVerticalGroup(
            jp_categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_categoriasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_categoria_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_categoria_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formCrud.setBackground(new java.awt.Color(255, 255, 255));
        formCrud.setPreferredSize(new java.awt.Dimension(599, 445));
        formCrud.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        formCrud.add(jPanel2, "card2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        t.setBackground(new java.awt.Color(255, 255, 255));

        btnCategorias.setBackground(new java.awt.Color(34, 197, 94));
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setText("CATEGORIAS");
        btnCategorias.setBorder(null);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setText("EMPLEADOS");
        btnEmpleados.setBorder(null);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34, 197, 94));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorder(null);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnRoles.setText("ROLES");
        btnRoles.setBorder(null);
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 197, 94));
        jLabel3.setText("D'Sami Store");

        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34, 197, 94));
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBorder(null);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tLayout = new javax.swing.GroupLayout(t);
        t.setLayout(tLayout);
        tLayout.setHorizontalGroup(
            tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRoles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
            .addGroup(tLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tLayout.setVerticalGroup(
            tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));
        content.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnIconSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnIconSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnIconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_icon.png"))); // NOI18N
        btnIconSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("administrador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(616, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnIconSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnIconSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        producto producto = new producto();
        producto.setSize(875, 629);
        
        content.removeAll();
        content.add(producto,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnProductos.setBackground(new java.awt.Color(34, 197, 94));
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34, 197, 94));
        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setForeground(new java.awt.Color(34, 197, 94));
        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34, 197, 94));
        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34, 197, 94));

    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
        categoria categoria = new categoria();
        categoria.setSize(875, 629);
        
        content.removeAll();
        content.add(categoria,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnCategorias.setBackground(new java.awt.Color(34, 197, 94));
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34, 197, 94));
        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34, 197, 94));
        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34, 197, 94));
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btn_categoria_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoria_agregarActionPerformed
        // TODO add your handling code here:
        categoria_editar_modal modal= new categoria_editar_modal();
        
        //JOptionPane.showMessageDialog(null,"gg");
        
        modal.setVisible(true);
       
    }//GEN-LAST:event_btn_categoria_agregarActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        empleado empleado = new empleado();
        empleado.setSize(875, 629);
        
        content.removeAll();
        content.add(empleado,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnEmpleados.setBackground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34, 197, 94));
        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setForeground(new java.awt.Color(34, 197, 94));
        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34, 197, 94));
        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        usuario usuario = new usuario();
        usuario.setSize(875, 629);
        
        content.removeAll();
        content.add(usuario,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnUsuarios.setBackground(new java.awt.Color(34, 197, 94));
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setForeground(new java.awt.Color(34, 197, 94));
        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34, 197, 94));
        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        // TODO add your handling code here:
        rol rol = new rol();
        rol.setSize(875, 629);
        
        content.removeAll();
        content.add(rol,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnRoles.setBackground(new java.awt.Color(34, 197, 94));
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34,197,94));
        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setForeground(new java.awt.Color(34,197,94));
        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setForeground(new java.awt.Color(34,197,94));
        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34,197,94));
        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnIconSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconSalirActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        proveedor proveedor = new proveedor();
        proveedor.setSize(875, 629);
        proveedor.setLocation (10,00);
        
        content.removeAll();
        content.add(proveedor,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnProveedores.setBackground(new java.awt.Color(34, 197, 94));
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setForeground(new java.awt.Color(34, 197, 94));
        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setForeground(new java.awt.Color(34, 197, 94));
        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setForeground(new java.awt.Color(34, 197, 94));
        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(34, 197, 94));
        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setForeground(new java.awt.Color(34, 197, 94));
    }//GEN-LAST:event_btnProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplicacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCategorias;
    public javax.swing.JButton btnEmpleados;
    public javax.swing.JButton btnIconSalir;
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnProveedores;
    public javax.swing.JButton btnRoles;
    public javax.swing.JButton btnUsuarios;
    public javax.swing.JButton btn_categoria_agregar;
    public javax.swing.JButton btn_categoria_buscar;
    public javax.swing.JButton btn_empleado_agregar;
    public javax.swing.JButton btn_empleado_buscar;
    public javax.swing.JButton btn_producto_agregar;
    public javax.swing.JButton btn_producto_buscar;
    public javax.swing.JButton btn_roles_agregar;
    public javax.swing.JButton btn_roles_buscar;
    public javax.swing.JButton btn_usuario_agregar;
    public javax.swing.JButton btn_usuario_buscar;
    public javax.swing.JPanel content;
    public javax.swing.JDesktopPane formCrud;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JPanel jp_categorias;
    public javax.swing.JPanel jp_empleados;
    public javax.swing.JPanel jp_productos;
    public javax.swing.JPanel jp_roles;
    public javax.swing.JPanel jp_usuarios;
    public java.awt.Label label1;
    public java.awt.Label label2;
    public java.awt.Label label3;
    public java.awt.Label label4;
    public java.awt.Label label5;
    public javax.swing.JPanel t;
    public javax.swing.JTable tb_categoria1;
    public javax.swing.JTable tb_categoria2;
    public javax.swing.JTable tb_empleado;
    public javax.swing.JTable tb_roles;
    public javax.swing.JTable tb_usuario;
    public javax.swing.JTextField txtCategoriaBuscar;
    public javax.swing.JTextField txtCategoriaBuscar1;
    public javax.swing.JTextField txtCategoriaBuscar2;
    public javax.swing.JTextField txtCategoriaBuscar3;
    public javax.swing.JTextField txtCategoriaBuscar4;
    // End of variables declaration//GEN-END:variables
}
