/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsamistore_mockup.panels;

import dsamistore_mockup.modals.producto_eliminar_modal;
import dsamistore_mockup.producto_agregar_modal;
import dsamistore_mockup.producto_editar_modal;

/**
 *
 * @author OSCAR
 */
public class producto extends javax.swing.JPanel {

    /**
     * Creates new form producto
     */
    public producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProductos = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        btnProductoAgregar = new javax.swing.JButton();
        txtProductoBuscar = new javax.swing.JTextField();
        btnProductoBuscar = new javax.swing.JButton();
        jspProductos = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        btnProductoModificar = new javax.swing.JButton();
        btnProductoEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jpProductos.setBackground(new java.awt.Color(255, 255, 255));
        jpProductos.setName("jpProductos"); // NOI18N

        label5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label5.setText("Producto");

        btnProductoAgregar.setBackground(new java.awt.Color(34, 197, 94));
        btnProductoAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProductoAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoAgregar.setText("AGREGAR");
        btnProductoAgregar.setToolTipText("");
        btnProductoAgregar.setAutoscrolls(true);
        btnProductoAgregar.setBorder(null);
        btnProductoAgregar.setBorderPainted(false);
        btnProductoAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoAgregarActionPerformed(evt);
            }
        });

        btnProductoBuscar.setBackground(new java.awt.Color(34, 197, 94));
        btnProductoBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProductoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoBuscar.setText("BUSCAR");
        btnProductoBuscar.setToolTipText("");
        btnProductoBuscar.setAutoscrolls(true);
        btnProductoBuscar.setBorder(null);
        btnProductoBuscar.setBorderPainted(false);
        btnProductoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Categoria", "Nombre", "Descripcion", "Precio", "Estado"
            }
        ));
        jspProductos.setViewportView(tbProducto);

        btnProductoModificar.setBackground(new java.awt.Color(34, 197, 94));
        btnProductoModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProductoModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoModificar.setText("MODIFICAR");
        btnProductoModificar.setToolTipText("");
        btnProductoModificar.setAutoscrolls(true);
        btnProductoModificar.setBorder(null);
        btnProductoModificar.setBorderPainted(false);
        btnProductoModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoModificarActionPerformed(evt);
            }
        });

        btnProductoEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnProductoEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProductoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoEliminar.setText("ELIMINAR");
        btnProductoEliminar.setBorder(null);
        btnProductoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpProductosLayout = new javax.swing.GroupLayout(jpProductos);
        jpProductos.setLayout(jpProductosLayout);
        jpProductosLayout.setHorizontalGroup(
            jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProductosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProductosLayout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProductosLayout.createSequentialGroup()
                        .addGroup(jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jspProductos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProductosLayout.createSequentialGroup()
                                .addComponent(btnProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(jpProductosLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btnProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpProductosLayout.setVerticalGroup(
            jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProductosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProductoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnProductoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoAgregarActionPerformed
        // TODO add your handling code here:
        producto_agregar_modal modal= new producto_agregar_modal();
        modal.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnProductoAgregarActionPerformed

    private void btnProductoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoModificarActionPerformed
        // TODO add your handling code here:
        producto_editar_modal modal= new producto_editar_modal();
        modal.setVisible(true);
    }//GEN-LAST:event_btnProductoModificarActionPerformed

    private void btnProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoEliminarActionPerformed
        // TODO add your handling code here:
        producto_eliminar_modal modal= new producto_eliminar_modal();
        modal.setVisible(true);
    }//GEN-LAST:event_btnProductoEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProductoAgregar;
    public javax.swing.JButton btnProductoBuscar;
    private javax.swing.JButton btnProductoEliminar;
    public javax.swing.JButton btnProductoModificar;
    public javax.swing.JPanel jpProductos;
    public javax.swing.JScrollPane jspProductos;
    private java.awt.Label label5;
    public javax.swing.JTable tbProducto;
    public javax.swing.JTextField txtProductoBuscar;
    // End of variables declaration//GEN-END:variables
}
