/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsamistore_mockup.panels;

import dsamistore_mockup.modals.rol_eliminar_modal;
import dsamistore_mockup.rol_agregar_modal;
import dsamistore_mockup.rol_editar_modal;

/**
 *
 * @author OSCAR
 */
public class rol extends javax.swing.JPanel {

    /**
     * Creates new form rol
     */
    public rol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRoles = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        btnRolesAgregar = new javax.swing.JButton();
        txtRolBuscar = new javax.swing.JTextField();
        btnRolesBuscar = new javax.swing.JButton();
        jspRoles = new javax.swing.JScrollPane();
        tbRoles = new javax.swing.JTable();
        btnRolModificar = new javax.swing.JButton();
        btnRolEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jpRoles.setBackground(new java.awt.Color(255, 255, 255));

        label4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label4.setText("Roles");

        btnRolesAgregar.setBackground(new java.awt.Color(34, 197, 94));
        btnRolesAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRolesAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnRolesAgregar.setText("AGREGAR");
        btnRolesAgregar.setToolTipText("");
        btnRolesAgregar.setAutoscrolls(true);
        btnRolesAgregar.setBorder(null);
        btnRolesAgregar.setBorderPainted(false);
        btnRolesAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRolesAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesAgregarActionPerformed(evt);
            }
        });

        btnRolesBuscar.setBackground(new java.awt.Color(34, 197, 94));
        btnRolesBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRolesBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnRolesBuscar.setText("BUSCAR");
        btnRolesBuscar.setToolTipText("");
        btnRolesBuscar.setAutoscrolls(true);
        btnRolesBuscar.setBorder(null);
        btnRolesBuscar.setBorderPainted(false);
        btnRolesBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tbRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Estado"
            }
        ));
        jspRoles.setViewportView(tbRoles);

        btnRolModificar.setBackground(new java.awt.Color(34, 197, 94));
        btnRolModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnRolModificar.setText("MODIFICAR");
        btnRolModificar.setBorder(null);
        btnRolModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolModificarActionPerformed(evt);
            }
        });

        btnRolEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnRolEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRolEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnRolEliminar.setText("ELIMINAR");
        btnRolEliminar.setBorder(null);
        btnRolEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRolesLayout = new javax.swing.GroupLayout(jpRoles);
        jpRoles.setLayout(jpRolesLayout);
        jpRolesLayout.setHorizontalGroup(
            jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRolesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRolesLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRolesLayout.createSequentialGroup()
                        .addGroup(jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jspRoles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpRolesLayout.createSequentialGroup()
                                .addComponent(btnRolesAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtRolBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRolesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(jpRolesLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btnRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpRolesLayout.setVerticalGroup(
            jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRolesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRolesAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRolesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jspRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRolesAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesAgregarActionPerformed
        // TODO add your handling code here:
        rol_agregar_modal modal= new rol_agregar_modal();
        modal.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnRolesAgregarActionPerformed

    private void btnRolModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolModificarActionPerformed
        // TODO add your handling code here:
        rol_editar_modal modal= new rol_editar_modal();
        modal.setVisible(true);
    }//GEN-LAST:event_btnRolModificarActionPerformed

    private void btnRolEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolEliminarActionPerformed
        // TODO add your handling code here:
        rol_eliminar_modal modal= new rol_eliminar_modal();
        modal.setVisible(true);
    }//GEN-LAST:event_btnRolEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRolEliminar;
    private javax.swing.JButton btnRolModificar;
    private javax.swing.JButton btnRolesAgregar;
    private javax.swing.JButton btnRolesBuscar;
    private javax.swing.JPanel jpRoles;
    private javax.swing.JScrollPane jspRoles;
    private java.awt.Label label4;
    private javax.swing.JTable tbRoles;
    private javax.swing.JTextField txtRolBuscar;
    // End of variables declaration//GEN-END:variables
}
